# Generated by Django 4.2.5 on 2023-09-25 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaMadre', models.CharField(max_length=40)),
                ('placaVideo', models.CharField(max_length=40)),
                ('procesador', models.CharField(max_length=40)),
                ('ram', models.CharField(max_length=40)),
                ('fuente', models.CharField(max_length=40)),
                ('almacenamiento', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teclado', models.CharField(max_length=40)),
                ('mouse', models.CharField(max_length=40)),
                ('monitor', models.CharField(max_length=40)),
                ('headset', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePlataforma', models.CharField(max_length=40)),
                ('user', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('plataforma', models.CharField(max_length=40)),
                ('dificultad', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('finalizado', models.BooleanField(default=0)),
            ],
        ),
    ]
